-- Snowflake target DDL
CREATE OR REPLACE TABLE RAW.PATIENTS (
    PATIENT_ID VARCHAR,
    PATIENT_NAME VARCHAR,
    DOB DATE,
    GENDER VARCHAR,
    CITY VARCHAR
);

CREATE OR REPLACE TABLE RAW.VISITS (
    VISIT_ID VARCHAR,
    PATIENT_ID VARCHAR,
    VISIT_DATE DATE,
    DEPARTMENT VARCHAR,
    BILLED_AMOUNT NUMBER(12,2),
    STATUS VARCHAR
);
