-- Curated layer
CREATE OR REPLACE VIEW ANALYTICS.VW_MONTHLY_REVENUE AS
SELECT
    DATE_TRUNC('MONTH', VISIT_DATE) AS REVENUE_MONTH,
    DEPARTMENT,
    COUNT(*) AS COMPLETED_VISITS,
    ROUND(SUM(BILLED_AMOUNT), 2) AS RECOGNIZED_REVENUE
FROM RAW.VISITS
WHERE STATUS = 'Completed'
GROUP BY 1,2;
